"""Pinned shipped pack ids — update when adding plugins/src/<id>/ (same contract as viz host tests)."""
from __future__ import annotations

# plugins/src/<id>/ with plugin.yml (sorted).
PINNED_SHIPPED_PLUGIN_IDS: tuple[str, ...] = (
    "air-bt",
    "air-ssid",
    "backrooms",
    "blob-mesh",
    "carousel",
    "cgroups",
    "command",
    "cores",
    "cpu-pong",
    "cpupong",
    "cypher-cic",
    "disk",
    "doom",
    "drone-show",
    "frogger",
    "gpu",
    "graph-fabric",
    "helix",
    "hn-rain",
    "hn-term",
    "invaders",
    "kefrens-bars",
    "lan-heat",
    "lan-pong",
    "lan-pulse",
    "layers",
    "load",
    "marble-run",
    "memory",
    "nest-cams",
    "netpong",
    "nixie-clock",
    "orbits",
    "packet-tunnel",
    "pacman",
    "portal",
    "protocols",
    "pulse-ts",
    "rf-constellation",
    "roto-proto",
    "services",
    "skyline",
    "sockets",
    "source-fabric",
    "source-web",
    "star-sines",
    "stereo-gram",
    "syscon",
    "talker-storm",
    "talkers",
    "tetris",
    "topology",
    "udev",
    "units",
    "watch",
    "waves",
)

PINNED_EXAMPLE_PACK_IDS: tuple[str, ...] = ("sample",)
