// GENERATED by web/scripts/build-pack-install-lint.mjs from plugins/sdk/pack-install-lint.ts (#186). Do not edit.
// `pnpm install` in web/ regenerates it (the `prepare` script); pack-install-lint-prebuilt.test.ts
// fails when it doesn't match a fresh build of the sources.
// plugins/sdk/pack-install-lint.ts
import fs4 from "node:fs";
import path4 from "node:path";

// plugins/sdk/pack-bundle-resolve.mjs
import fs from "node:fs";
import path from "node:path";
var PACK_BUNDLE_EXTERNALS = /* @__PURE__ */ new Set(["three", "d3-force-3d"]);
function stripImportSuffix(spec) {
  const q = spec.indexOf("?");
  return q >= 0 ? spec.slice(0, q) : spec;
}
function realpathSafe(abs) {
  try {
    return fs.realpathSync.native(abs);
  } catch {
    return null;
  }
}
function insideRoot(root, candidate) {
  const realRoot = realpathSafe(root);
  const realCand = realpathSafe(candidate);
  if (!realRoot || !realCand) return false;
  const rel = path.relative(realRoot, realCand);
  return rel === "" || !rel.startsWith("..") && !path.isAbsolute(rel);
}
function resolveWithExtensions(baseAbs) {
  const tries = [
    baseAbs,
    `${baseAbs}.ts`,
    `${baseAbs}.tsx`,
    `${baseAbs}.mts`,
    `${baseAbs}.js`,
    `${baseAbs}.mjs`,
    `${baseAbs}.json`,
    path.join(baseAbs, "index.ts")
  ];
  for (const candidate of tries) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return baseAbs;
}
function isRemoteSpecifier(spec) {
  return /^https?:\/\//i.test(stripImportSuffix(spec));
}
function isViteFsSpecifier(spec) {
  return stripImportSuffix(spec).startsWith("/@fs/");
}
function isBareModule(spec) {
  const bare = stripImportSuffix(spec);
  if (!bare || bare.startsWith(".") || bare.startsWith("/")) return false;
  if (bare.includes("plugins/sdk/")) return false;
  return true;
}
function resolvePackBundleImport(opts) {
  const { specifier, importerFile, packHome, sdkRoot, repoRoot } = opts;
  const bare = stripImportSuffix(specifier);
  if (!bare) {
    return { ok: false, code: "empty-specifier", reason: "empty import specifier" };
  }
  if (PACK_BUNDLE_EXTERNALS.has(bare)) {
    return { ok: true, external: true };
  }
  if (isRemoteSpecifier(bare)) {
    return { ok: false, code: "remote-import", reason: `remote URL imports are not allowed (${bare})` };
  }
  if (isViteFsSpecifier(bare)) {
    return { ok: false, code: "vite-fs-import", reason: `/@fs/ imports are not allowed (${bare})` };
  }
  if (path.isAbsolute(bare)) {
    return { ok: false, code: "absolute-import", reason: `absolute imports are not allowed (${bare})` };
  }
  if (isBareModule(bare)) {
    return { ok: false, code: "bare-module", reason: `bare module imports are not allowed (${bare}); only three and d3-force-3d are external` };
  }
  const importerDir = path.dirname(importerFile);
  let abs;
  const packSdkRel = bare.match(/^(?:\.\.\/)+sdk\/(.+)$/);
  if (packSdkRel) {
    const candidate = resolveWithExtensions(path.normalize(path.join(sdkRoot, packSdkRel[1])));
    if (!insideRoot(sdkRoot, candidate)) {
      return {
        ok: false,
        code: "outside-boundary",
        reason: `import escapes pack and SDK (${bare})`,
        resolved: candidate
      };
    }
    abs = candidate;
  } else if (bare.startsWith(".")) {
    abs = resolveWithExtensions(path.normalize(path.join(importerDir, bare)));
  } else if (bare.includes("plugins/sdk/") || bare.startsWith("plugins/sdk/")) {
    const tail = bare.replace(/^.*plugins\/sdk\//, "");
    abs = resolveWithExtensions(path.join(sdkRoot, tail));
  } else if (repoRoot && (bare.includes("plugins/src/") || bare.startsWith("plugins/src/"))) {
    abs = resolveWithExtensions(path.join(repoRoot, bare.replace(/^\.\/+/, "")));
  } else {
    return { ok: false, code: "unknown-specifier", reason: `unsupported import (${bare})` };
  }
  const real = realpathSafe(abs);
  if (!real || !fs.existsSync(real)) {
    return { ok: false, code: "missing-file", reason: `import resolves to missing file (${bare})` };
  }
  if (insideRoot(packHome, real)) {
    return { ok: true, path: real, zone: "pack" };
  }
  if (insideRoot(sdkRoot, real)) {
    return { ok: true, path: real, zone: "sdk" };
  }
  return {
    ok: false,
    code: "outside-boundary",
    reason: `import escapes pack and SDK (${bare})`,
    resolved: real
  };
}

// plugins/sdk/pack-lint.ts
import fs3 from "node:fs";
import path3 from "node:path";

// plugins/sdk/pack-lint-import.ts
import fs2 from "node:fs";
import path2 from "node:path";
var PACK_BOUNDARY_FIX_HINT = "Use `import type` from `plugins/sdk/viz-contract`; for runtime helpers use `plugins/sdk/*` (bundled at pack build) or copy the code into your pack.";
function maskComments(source) {
  const out = [];
  let i = 0;
  const len = source.length;
  while (i < len) {
    const ch = source[i];
    const next = source[i + 1];
    if (ch === "/" && next === "/") {
      while (i < len && source[i] !== "\n") {
        out.push(" ");
        i++;
      }
      continue;
    }
    if (ch === "/" && next === "*") {
      out.push(" ", " ");
      i += 2;
      while (i < len - 1 && !(source[i] === "*" && source[i + 1] === "/")) {
        out.push(source[i] === "\n" ? "\n" : " ");
        i++;
      }
      if (i < len - 1) {
        out.push(" ", " ");
        i += 2;
      }
      continue;
    }
    if (ch === "'" || ch === '"') {
      const q = ch;
      out.push(ch);
      i++;
      while (i < len) {
        const c = source[i];
        out.push(c);
        i++;
        if (c === "\\" && i < len) {
          out.push(source[i]);
          i++;
          continue;
        }
        if (c === q) break;
      }
      continue;
    }
    if (ch === "`") {
      out.push(ch);
      i++;
      while (i < len) {
        const c = source[i];
        out.push(c);
        i++;
        if (c === "\\" && i < len) {
          out.push(source[i]);
          i++;
          continue;
        }
        if (c === "`") break;
        if (c === "$" && source[i] === "{") {
          out.push("{");
          i++;
          let depth = 1;
          while (i < len && depth > 0) {
            const d = source[i];
            out.push(d);
            i++;
            if (d === "{") depth++;
            else if (d === "}") depth--;
          }
        }
      }
      continue;
    }
    out.push(ch);
    i++;
  }
  return out.join("");
}
function lineColAt(source, index) {
  let line = 1;
  let column = 1;
  for (let i = 0; i < index && i < source.length; i++) {
    if (source[i] === "\n") {
      line++;
      column = 1;
    } else {
      column++;
    }
  }
  return { line, column };
}
function isInStringOrTemplateLiteral(source, index) {
  let i = 0;
  while (i < index && i < source.length) {
    const ch = source[i];
    const next = source[i + 1];
    if (ch === "/" && next === "/") {
      while (i < source.length && source[i] !== "\n") i++;
      continue;
    }
    if (ch === "/" && next === "*") {
      i += 2;
      while (i < source.length - 1 && !(source[i] === "*" && source[i + 1] === "/")) i++;
      i += 2;
      continue;
    }
    if (ch === "'" || ch === '"') {
      const q = ch;
      i++;
      while (i < source.length) {
        const c = source[i];
        if (c === "\\") {
          i += 2;
          continue;
        }
        if (c === q) {
          i++;
          break;
        }
        if (i >= index) return true;
        i++;
      }
      continue;
    }
    if (ch === "`") {
      i++;
      while (i < source.length) {
        const c = source[i];
        if (c === "\\") {
          i += 2;
          continue;
        }
        if (c === "`") {
          i++;
          break;
        }
        if (c === "$" && source[i + 1] === "{") {
          i += 2;
          let depth = 1;
          while (i < source.length && depth > 0) {
            if (i >= index) return true;
            const d = source[i];
            if (d === "{") depth++;
            else if (d === "}") depth--;
            i++;
          }
          continue;
        }
        if (i >= index) return true;
        i++;
      }
      continue;
    }
    i++;
  }
  return false;
}
function stripImportSuffix2(spec) {
  const q = spec.indexOf("?");
  return q >= 0 ? spec.slice(0, q) : spec;
}
function readStringLiteral(source, start) {
  const q = source[start];
  if (q !== "'" && q !== '"') return null;
  let i = start + 1;
  let value = "";
  while (i < source.length) {
    const ch = source[i];
    if (ch === "\\") {
      value += ch + (source[i + 1] ?? "");
      i += 2;
      continue;
    }
    if (ch === q) return { value, end: i + 1 };
    value += ch;
    i++;
  }
  return null;
}
function readTemplateLiteral(source, start) {
  if (source[start] !== "`") return null;
  let i = start + 1;
  let value = "";
  let hasExpr = false;
  while (i < source.length) {
    const ch = source[i];
    if (ch === "\\") {
      i += 2;
      continue;
    }
    if (ch === "`") return { value, end: i + 1, hasExpr };
    if (ch === "$" && source[i + 1] === "{") {
      hasExpr = true;
      i += 2;
      let depth = 1;
      while (i < source.length && depth > 0) {
        const c = source[i];
        if (c === "{") depth++;
        else if (c === "}") depth--;
        i++;
      }
      continue;
    }
    value += ch;
    i++;
  }
  return null;
}
function parseRuntimeCall(source, index, call) {
  let i = index + call.length;
  while (i < source.length && /\s/.test(source[i])) i++;
  if (source[i] !== "(") {
    return { kind: "unverified", call, raw: `${call}(?)`, index };
  }
  i++;
  while (i < source.length && /\s/.test(source[i])) i++;
  const ch = source[i];
  if (ch === "'" || ch === '"') {
    const lit = readStringLiteral(source, i);
    if (lit) return { kind: call === "import" ? "dynamic" : "require", specifier: lit.value, index };
  }
  if (ch === "`") {
    const lit = readTemplateLiteral(source, i);
    if (lit) {
      const inner = source.slice(i + 1, lit.end - 1);
      const hostSpec = inner.replace(/\$\{[^}]*\}/g, "*");
      if (lit.hasExpr) {
        return { kind: "unverified", call, raw: `${call}(\`…\${…}\`)`, index, hostSpec };
      }
      return { kind: call === "import" ? "dynamic" : "require", specifier: lit.value, index };
    }
  }
  if (ch === ")") {
    return { kind: "unverified", call, raw: `${call}()`, index };
  }
  const rest = source.slice(i, Math.min(source.length, i + 40)).replace(/\s+/g, " ");
  return { kind: "unverified", call, raw: `${call}(${rest.split(")")[0] ?? "?"})`, index };
}
function extractPackImports(source) {
  const masked = maskComments(source);
  const out = [];
  const staticRe = /\bimport\s+(?:type\s+)?[\s\S]*?\sfrom\s+["']([^"']+)["']/g;
  let m;
  while ((m = staticRe.exec(masked)) !== null) {
    out.push({ kind: "static", specifier: m[1], index: m.index });
  }
  const exportRe = /\bexport\s+(?:type\s+)?(?:\{[^}]*\}|\*(?:\s+as\s+\w+)?)\s+from\s+["']([^"']+)["']/g;
  while ((m = exportRe.exec(masked)) !== null) {
    out.push({ kind: "export-from", specifier: m[1], index: m.index });
  }
  const sideRe = /\bimport\s+["']([^"']+)["']\s*(?:;|$)/gm;
  while ((m = sideRe.exec(masked)) !== null) {
    const before = masked.slice(Math.max(0, m.index - 12), m.index);
    if (/\bfrom\s*$/i.test(before) || /\bfrom\s+["']/.test(before)) continue;
    out.push({ kind: "side-effect", specifier: m[1], index: m.index });
  }
  const callRe = /\b(import|require)\s*\(/g;
  while ((m = callRe.exec(masked)) !== null) {
    const call = m[1];
    if (isInStringOrTemplateLiteral(masked, m.index)) continue;
    const prevChar = m.index > 0 ? masked[m.index - 1] : "";
    if (prevChar === ".") continue;
    const prev = masked.slice(Math.max(0, m.index - 8), m.index);
    if (call === "import" && /\bimport\s*$/.test(prev.replace(/^\s+/, ""))) continue;
    out.push(parseRuntimeCall(masked, m.index, call));
  }
  return out;
}
function isSdkSpecifier(spec) {
  const bare = stripImportSuffix2(spec);
  if (bare.includes("/plugins/sdk/")) return true;
  return /^(?:\.\.\/)+sdk\//.test(bare);
}
function isRemoteSpecifier2(spec) {
  return /^https?:\/\//i.test(stripImportSuffix2(spec));
}
function isViteFsSpecifier2(spec) {
  return stripImportSuffix2(spec).startsWith("/@fs/");
}
function pathInsidePack(fileAbs, packDirAbs) {
  try {
    const realFile = fs2.realpathSync.native(fileAbs);
    const realPack = fs2.realpathSync.native(packDirAbs);
    const rel = path2.relative(realPack, realFile);
    return rel === "" || !rel.startsWith("..") && !path2.isAbsolute(rel);
  } catch {
    return false;
  }
}
function resolveRelativeAbs(importerDirAbs, bare) {
  let abs = path2.normalize(path2.join(importerDirAbs, bare));
  for (const ext of [".ts", ".tsx", ".mts", "/index.ts"]) {
    const candidate = ext.startsWith("/") ? `${abs}${ext}` : `${abs}${ext}`;
    if (fs2.existsSync(candidate)) {
      return candidate;
    }
  }
  return abs;
}
function repoRelFromAbs(absPath, repoRoot) {
  try {
    const real = fs2.realpathSync.native(absPath);
    const repoRel = path2.relative(repoRoot, real).replace(/\\/g, "/");
    if (repoRel.startsWith("../")) return null;
    return repoRel;
  } catch {
    return null;
  }
}
function resolveSpecifierRepoRel(spec, importerDirAbs, repoRoot) {
  const bare = stripImportSuffix2(spec);
  if (!bare) return null;
  if (isViteFsSpecifier2(bare)) {
    let absFs = path2.normalize(decodeURIComponent(bare.slice("/@fs/".length)));
    if (!fs2.existsSync(absFs)) {
      const idx = absFs.replace(/\\/g, "/").indexOf("plugins/src/");
      if (idx >= 0) absFs = path2.join(repoRoot, absFs.slice(idx));
    }
    return repoRelFromAbs(absFs, repoRoot);
  }
  if (isRemoteSpecifier2(bare)) {
    try {
      const pathname = new URL(bare).pathname.replace(/\\/g, "/");
      const idx = pathname.indexOf("/plugins/src/");
      if (idx >= 0) {
        return repoRelFromAbs(path2.join(repoRoot, pathname.slice(idx + 1)), repoRoot);
      }
    } catch {
      return null;
    }
    return null;
  }
  if (bare.startsWith(".")) {
    const abs = resolveRelativeAbs(importerDirAbs, bare);
    const fromReal = repoRelFromAbs(abs, repoRoot);
    if (fromReal) return fromReal;
    const rel = path2.relative(repoRoot, abs).replace(/\\/g, "/");
    return rel.startsWith("../") ? null : rel;
  }
  if (bare.includes("plugins/src/") || bare.startsWith("plugins/src/")) {
    return repoRelFromAbs(path2.join(repoRoot, bare.replace(/^\.\/+/, "")), repoRoot);
  }
  return null;
}
function classifyPackSpecifier(spec, packRepoPrefix, importerDirAbs, repoRoot, packDirAbs) {
  const bare = stripImportSuffix2(spec);
  const packPrefix = `${packRepoPrefix.replace(/\/$/, "")}/`;
  const packIdFromPrefix = packPrefix.match(/plugins\/src\/([^/]+)\//)?.[1];
  const sdkRootAbs = path2.join(repoRoot, "plugins/sdk");
  if (packDirAbs && fs2.existsSync(sdkRootAbs)) {
    const importerFile = path2.join(importerDirAbs, "_lint_module.ts");
    const bundle = resolvePackBundleImport({
      specifier: spec,
      importerFile,
      packHome: packDirAbs,
      sdkRoot: sdkRootAbs,
      repoRoot
    });
    if (bundle.ok) return "ok";
    if (bundle.code === "remote-import" || bundle.code === "vite-fs-import" || bundle.code === "absolute-import" || bundle.code === "bare-module" || bundle.code === "unknown-specifier") {
      return "host-import";
    }
  } else if (isSdkSpecifier(bare)) {
    return "ok";
  }
  if (bare.includes("web/src/")) return "host-import";
  if (bare.startsWith(".") && packDirAbs) {
    const abs = resolveRelativeAbs(importerDirAbs, bare);
    if (pathInsidePack(abs, packDirAbs)) return "ok";
  }
  if (isRemoteSpecifier2(bare)) {
    const resolved2 = resolveSpecifierRepoRel(bare, importerDirAbs, repoRoot);
    if (resolved2?.startsWith("plugins/src/") && packIdFromPrefix && !resolved2.startsWith(`plugins/src/${packIdFromPrefix}/`)) {
      return "cross-pack-import";
    }
    return "host-import";
  }
  if (isViteFsSpecifier2(bare)) {
    const resolved2 = resolveSpecifierRepoRel(bare, importerDirAbs, repoRoot);
    if (resolved2?.startsWith("plugins/src/")) {
      return packIdFromPrefix && resolved2.startsWith(`plugins/src/${packIdFromPrefix}/`) ? "ok" : "cross-pack-import";
    }
    return "host-import";
  }
  const barePack = bare.match(/(?:^|\/)plugins\/src\/([^/]+)/);
  if (barePack && packIdFromPrefix && barePack[1] !== packIdFromPrefix) return "cross-pack-import";
  if (!bare.startsWith(".")) return "ok";
  const resolved = resolveSpecifierRepoRel(bare, importerDirAbs, repoRoot);
  if (!resolved) return "host-import";
  if (resolved.startsWith("plugins/sdk/")) return "ok";
  if (resolved.startsWith(packPrefix)) return "ok";
  if (resolved.startsWith("plugins/src/")) return "cross-pack-import";
  if (resolved.includes("web/src/")) return "host-import";
  return "host-import";
}
function packSymlinkEscapes(packDirAbs, packRepoPrefix, repoRoot) {
  if (!fs2.existsSync(packDirAbs)) return [];
  const packPrefix = `${packRepoPrefix.replace(/\/$/, "")}/`;
  const hits = [];
  const walk = (rel) => {
    const dir = path2.join(packDirAbs, rel);
    for (const ent of fs2.readdirSync(dir, { withFileTypes: true })) {
      const sub = rel ? `${rel}/${ent.name}` : ent.name;
      const full = path2.join(packDirAbs, sub);
      if (ent.isSymbolicLink()) {
        try {
          const real = fs2.realpathSync.native(full);
          const repoRel = path2.relative(repoRoot, real).replace(/\\/g, "/");
          if (!repoRel.startsWith(packPrefix)) {
            hits.push({
              file: `${packPrefix}${sub}`.replace(/\\/g, "/"),
              target: repoRel,
              detail: `symlink escape → ${ent.name}`
            });
          }
        } catch {
          hits.push({
            file: `${packPrefix}${sub}`.replace(/\\/g, "/"),
            target: "unresolvable-symlink",
            detail: ent.name
          });
        }
        continue;
      }
      if (ent.isDirectory()) walk(sub);
    }
  };
  walk("");
  return hits;
}

// plugins/sdk/pack-lint-types.ts
function violationKey(v) {
  return `${v.file}\0${v.rule}\0${v.target}`;
}

// plugins/sdk/legacy-zoto-pack-allowlist.ts
var LEGACY_DECLARE_ZOTO_PACK_IDS = [
  "ant-colony",
  "aquarium",
  "koi-pond",
  "metro-lines",
  "rocket-car-soccer",
  "voxel-world"
];
var LEGACY_ZOTO_ALLOWLIST_RULES = /* @__PURE__ */ new Set(["inline-zoto-declare"]);
function packIdFromPluginsSrcPath(file) {
  const m = file.match(/^plugins\/src\/([^/]+)\//);
  return m?.[1] ?? null;
}
function isLegacyDeclareZotoPackAllowed(packId) {
  return LEGACY_DECLARE_ZOTO_PACK_IDS.includes(packId);
}
function legacyZotoViolationsOnDisallowedPacks(violations) {
  return violations.filter((v) => {
    if (!LEGACY_ZOTO_ALLOWLIST_RULES.has(v.rule)) return false;
    const packId = packIdFromPluginsSrcPath(v.file);
    return packId != null && !isLegacyDeclareZotoPackAllowed(packId);
  });
}

// plugins/sdk/viz-zoto.ts
var VIZ_ZOTO_TYPE_MODULE = "plugins/sdk/viz-zoto";
var PACK_ZOTO_BINDING_HINT = `Use getVizZoto() from "${VIZ_ZOTO_TYPE_MODULE}" (e.g. const host = getVizZoto();), not a top-level zoto binding.`;
var INLINE_ZOTO_DECLARE_HINT = `Use getVizZoto() from "${VIZ_ZOTO_TYPE_MODULE}" instead of an inline zoto declaration.`;

// plugins/sdk/pack-lint-hints.ts
function formatViolationMessage(v) {
  const msg = ruleMessage(v.rule, v);
  const hint = ruleHint(v.rule, v);
  return hint ? `${msg} — ${hint}` : msg;
}
function ruleHint(rule, v) {
  switch (rule) {
    case "host-import":
    case "cross-pack-import":
      return PACK_BOUNDARY_FIX_HINT;
    case "unverified-import-call":
      return 'Use a string path inside your pack, e.g. `import("./scenes/a")`.';
    case "side-effect-import":
      return 'Side-effect imports are only allowed for files inside your pack (e.g. `import "./setup"`). Out-of-pack side effects bypass the bundle boundary.';
    case "sandbox-escape":
      return "Pack code runs in a sandboxed iframe — do not touch parent, storage, or cookies.";
    case "host-transport-escape":
      return v.detail ?? "Use getVizZoto() in the sandbox; do not call postMessage or import host transport types.";
    case "inline-zoto-declare":
    case "pack-zoto-binding":
      return v.detail ?? "Use getVizZoto() from plugins/sdk/viz-zoto (const host = getVizZoto();).";
    case "get-config-in-on-frame":
      return "Read config in onConfig or once at init with getConfig(); do not call getConfig() from onFrame.";
    case "host-imports-pack-src":
      return "Load shipped packs only via /api/plugins/<id>/module.js (no direct plugins/src imports).";
    case "glsl-uniform-undeclared":
      return "Declare `uniform <type> NAME;` in that stage (or the GLSL const it interpolates). A missing declaration fails the shader compile and leaves the tile bare (#171).";
    case "uniform-set-undeclared":
      return "Declare the uniform in the shader it is bound to, or stop setting it (a pack can only set host sky uniforms).";
    case "glsl-uniform-unset":
      return "Set it in the material's uniforms / onBeforeCompile (or use a host sky uniform in a pack sky).";
    case "uniform-type-conflict":
      return "Use the host's type for that uniform (or drop the declaration: the host preamble already declares it). A mismatch fails the sky compile or runs it against the wrong type.";
    case "write-uniform-not-in-manifest":
      return "List the uniform under `viz.uniforms` in plugin.yml (it must be a pack sky uniform), or stop writing it.";
    default:
      return "";
  }
}
function ruleMessage(rule, v) {
  const loc = v.line != null ? `\`${v.file}:${v.line}\`` : v.file;
  switch (rule) {
    case "unverified-import-call":
      return `${loc} ${v.detail ?? v.target} can't be checked.`;
    case "host-import":
      return `${loc} imports host or out-of-pack code (\`${v.target}\`).`;
    case "cross-pack-import":
      return `${loc} imports another pack (\`${v.target}\`).`;
    case "side-effect-import":
      return `${loc} side-effect import targets out-of-pack \`${v.target}\`.`;
    case "sandbox-escape":
      return `${loc} uses forbidden sandbox API (${v.target}).`;
    case "host-transport-escape":
      return `${loc} reaches host transport (${v.target}).`;
    case "inline-zoto-declare":
      return `${loc} declares zoto inline.`;
    case "pack-zoto-binding":
      return `${loc} binds top-level identifier zoto.`;
    case "get-config-in-on-frame":
      return `${loc} calls getConfig() inside onFrame.`;
    case "host-imports-pack-src":
      return `${loc} reaches pack source (\`${v.target}\`).`;
    case "glsl-uniform-undeclared": {
      const [stage, name] = v.target.split(":");
      return `${loc} ${stage} shader reads undeclared uniform ${name}.`;
    }
    case "uniform-set-undeclared":
      return `${loc} binds uniform ${v.target}, which its GLSL never declares.`;
    case "glsl-uniform-unset": {
      const [stage, name] = v.target.split(":");
      return `${loc} ${stage} shader reads uniform ${name}, which nothing sets.`;
    }
    case "uniform-type-conflict": {
      const [stage, name] = v.target.split(":");
      return `${loc} ${stage} shader ${v.detail ?? `redeclares host uniform ${name} with a different type`}.`;
    }
    case "write-uniform-not-in-manifest":
      return `${loc} ${v.detail ?? `writeUniform("${v.target}") isn't in plugin.yml viz.uniforms; the host drops the write`}.`;
    default:
      return `${loc} ${rule} → ${v.target}`;
  }
}
var PACK_LINT_PLAIN_SUMMARY = {
  "sandbox-escape": "it tries to reach outside its sandbox.",
  "host-transport-escape": "it tries to talk to the app directly, which packs aren't allowed to do.",
  "inline-zoto-declare": "it connects to the visualiser in an old way that isn't allowed any more.",
  "pack-zoto-binding": "it connects to the visualiser in an old way that isn't allowed any more.",
  "host-import": "it loads code from outside its own folder.",
  "cross-pack-import": "it loads code from another pack.",
  "side-effect-import": "it loads code from outside its own folder.",
  "unverified-import-call": "it loads code in a way that can't be checked.",
  "get-config-in-on-frame": "it reads its settings in a way that isn't allowed.",
  "host-imports-pack-src": "it loads code from outside its own folder.",
  // #171b's uniform rules (combined with #185). The install lint doesn't block on them today
  // (INSTALL_BLOCK_RULES), so these only keep the table complete.
  "glsl-uniform-undeclared": "it reads a shader setting it never declares.",
  "glsl-uniform-unset": "it reads a shader setting that nothing sets.",
  "uniform-set-undeclared": "it sets a shader setting its shader never declares.",
  "uniform-type-conflict": "it redefines one of the app's shader settings with a different type.",
  "write-uniform-not-in-manifest": "it writes a shader setting it doesn't list in its manifest."
};
var PACK_LINT_PLAIN_FALLBACK = "it uses code the pack sandbox doesn't allow.";
function plainBlockSummary(violations) {
  const sentences = [];
  for (const v of violations) {
    const s = PACK_LINT_PLAIN_SUMMARY[v.rule] ?? PACK_LINT_PLAIN_FALLBACK;
    if (!sentences.includes(s)) sentences.push(s);
  }
  if (!sentences.length) sentences.push(PACK_LINT_PLAIN_FALLBACK);
  return sentences.map((s, i) => i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)).join(" ");
}

// plugins/sdk/host-pack-src-import-allowlist.ts
var HOST_PACK_SRC_IMPORT_ALLOWLIST = [
  "backrooms",
  // debt: web/src/app/main.ts, web/src/audio/plugin-sfx.ts, host tests
  "hn-rain",
  // debt: web/src/app/main.ts, hn-rain-stills.ts, viz-pack-host.ts
  "hn-term",
  // debt: web/src/plugins/viz-pack-host.ts
  "marble-run",
  // debt: web/src/plugins/marble-run.test.ts (tests excluded from guard; pack used in host fixtures)
  "nixie-clock",
  // debt: web/src/plugins/viz-pack-host.ts
  "packet-tunnel",
  // debt: web/src/plugins/viz-pack-host.ts, dogfood tests
  "stereo-gram"
  // debt: web/src/app/main.ts, stereo-ai.ts, viz-pack-host.ts
];
var HOST_PACK_SRC_IMPORT_ALLOWLIST_COUNT = HOST_PACK_SRC_IMPORT_ALLOWLIST.length;

// plugins/sdk/pack-lint.ts
var SANDBOX_RULES = [
  { target: "parent.", re: /\bparent\s*\./ },
  { target: "typeof parent", re: /\btypeof\s+parent\b/ },
  { target: "window.parent", re: /\bwindow\.parent\b/ },
  { target: "window.top", re: /\bwindow\.top\b/ },
  { target: "top.", re: /\btop\s*\./ },
  { target: "document.cookie", re: /\bdocument\.cookie\b/ },
  { target: "localStorage", re: /\blocalStorage\b/ },
  { target: "sessionStorage", re: /\bsessionStorage\b/ },
  { target: "indexedDB", re: /\bindexedDB\b/ }
];
function withLoc(repoRel, source, index, v) {
  const { line, column } = lineColAt(source, index);
  return { ...v, file: repoRel, line, column };
}
var HOST_TRANSPORT_RULES = [
  { target: "postMessage", re: /\bpostMessage\s*\(/ },
  { target: "host-message-import", re: /\bfrom\s+["'][^"']*web\/src\/plugins\/host/ },
  {
    target: "host-message-type",
    re: /\bfrom\s+["'][^"']*(?:HostMsg|ParentMsg|zoto-viz-host|zoto-viz-plugin)/
  }
];
function hostTransportViolations(repoRel, text) {
  const code = maskComments(text);
  for (const { target, re } of HOST_TRANSPORT_RULES) {
    const m = re.exec(code);
    if (m) {
      return [withLoc(repoRel, text, m.index, {
        rule: "host-transport-escape",
        target,
        detail: "Packs and plugins/sdk must not call postMessage or import host transport types; use getVizZoto() in the sandbox."
      })];
    }
  }
  return [];
}
function sandboxViolations(repoRel, text) {
  const code = maskComments(text);
  for (const { target, re } of SANDBOX_RULES) {
    const m = re.exec(code);
    if (m) {
      return [withLoc(repoRel, text, m.index, { rule: "sandbox-escape", target })];
    }
  }
  return [];
}
function importBoundaryViolations(repoRel, text, packRepoPrefix, repoRoot, importerDirAbs, packDirAbs) {
  const hits = [];
  for (const site of extractPackImports(text)) {
    if (site.kind === "unverified") {
      hits.push(
        withLoc(repoRel, text, site.index, {
          rule: "unverified-import-call",
          target: site.call === "import" ? "import(non-literal)" : "require(non-literal)",
          detail: site.raw
        })
      );
      continue;
    }
    const rule = classifyPackSpecifier(site.specifier, packRepoPrefix, importerDirAbs, repoRoot, packDirAbs);
    if (rule === "ok") continue;
    if (site.kind === "side-effect") {
      hits.push(
        withLoc(repoRel, text, site.index, {
          rule: "side-effect-import",
          target: site.specifier
        })
      );
      continue;
    }
    hits.push(
      withLoc(repoRel, text, site.index, {
        rule,
        target: site.specifier
      })
    );
  }
  return hits;
}
function inlineZotoDeclare(repoRel, text) {
  const code = maskComments(text);
  const m = /\bdeclare\s+const\s+zoto\b/.exec(code);
  if (!m) return [];
  return [{
    file: repoRel,
    line: lineColAt(text, m.index).line,
    column: lineColAt(text, m.index).column,
    rule: "inline-zoto-declare",
    target: "declare-const-zoto",
    detail: INLINE_ZOTO_DECLARE_HINT
  }];
}
function topLevelZotoBinding(repoRel, text) {
  const code = maskComments(text);
  const hits = [];
  const re = /(?:^|\n)\s*(?:export\s+)?(?:const|let|var|function|class)\s+zoto\b/g;
  let m;
  while ((m = re.exec(code)) !== null) {
    const lineStart = code.lastIndexOf("\n", m.index) + 1;
    const lineEnd = code.indexOf("\n", m.index);
    const line = code.slice(lineStart, lineEnd < 0 ? code.length : lineEnd);
    if (/\bdeclare\b/.test(line)) continue;
    hits.push(withLoc(repoRel, text, m.index, {
      rule: "pack-zoto-binding",
      target: "top-level-zoto",
      detail: PACK_ZOTO_BINDING_HINT
    }));
  }
  return hits;
}
function getConfigInOnFrame(repoRel, text) {
  const code = maskComments(text);
  const assignRe = /[a-zA-Z_$][\w$]*\.onFrame\s*=\s*(\([^)]*\)|[a-zA-Z_$][\w$]*)\s*=>\s*\{/g;
  let m;
  while ((m = assignRe.exec(code)) !== null) {
    const start = m.index + m[0].length;
    const body = extractBracedBlock(code, start - 1);
    if (body && /\bgetConfig\s*\(/.test(body)) {
      return [{
        file: repoRel,
        line: lineColAt(text, m.index).line,
        rule: "get-config-in-on-frame",
        target: "getConfig()"
      }];
    }
  }
  const fnRe = /[a-zA-Z_$][\w$]*\.onFrame\s*=\s*function\s*\([^)]*\)\s*\{/g;
  while ((m = fnRe.exec(code)) !== null) {
    const start = m.index + m[0].length;
    const body = extractBracedBlock(code, start - 1);
    if (body && /\bgetConfig\s*\(/.test(body)) {
      return [{
        file: repoRel,
        line: lineColAt(text, m.index).line,
        rule: "get-config-in-on-frame",
        target: "getConfig()"
      }];
    }
  }
  return [];
}
function extractBracedBlock(code, openBraceIndex) {
  if (code[openBraceIndex] !== "{") return null;
  let depth = 0;
  for (let i = openBraceIndex; i < code.length; i++) {
    const ch = code[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return code.slice(openBraceIndex, i + 1);
    }
  }
  return null;
}
function symlinkViolations(packDirAbs, packRepoPrefix, repoRoot) {
  return packSymlinkEscapes(packDirAbs, packRepoPrefix, repoRoot).map((h) => ({
    file: h.file,
    rule: "host-import",
    target: h.target,
    detail: h.detail
  }));
}
function lintPackSource(repoRel, text, packRepoPrefix, repoRoot, importerDirAbs, packDirAbs) {
  const merged = [
    ...sandboxViolations(repoRel, text),
    ...hostTransportViolations(repoRel, text),
    ...importBoundaryViolations(repoRel, text, packRepoPrefix, repoRoot, importerDirAbs, packDirAbs),
    ...inlineZotoDeclare(repoRel, text),
    ...topLevelZotoBinding(repoRel, text),
    ...getConfigInOnFrame(repoRel, text)
  ];
  const seen = /* @__PURE__ */ new Set();
  return merged.filter((v) => {
    const k = violationKey(v);
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}
var PACK_FRONTEND_SCRIPT_EXTENSIONS = [".js", ".mjs", ".cjs", ".jsx", ".tsx", ".mts", ".cts"];
function isTsSource(name) {
  return name.endsWith(".ts") && !name.endsWith(".d.ts");
}
function isFrontendScript(name) {
  if (/\.d\.[mc]?ts$/.test(name)) return false;
  return PACK_FRONTEND_SCRIPT_EXTENSIONS.some((ext) => name.endsWith(ext));
}
function manifestFrontendEntries(packDirAbs) {
  let yml = "";
  for (const name of ["plugin.yml", "plugin.yaml"]) {
    try {
      yml = fs3.readFileSync(path3.join(packDirAbs, name), "utf8");
      break;
    } catch {
    }
  }
  const clean = (v) => (v ?? "").replace(/\s+#.*$/, "").trim().replace(/^(["'])(.*)\1$/, "$2").trim();
  const out = [];
  const top = clean(yml.match(/^entry:[ \t]*(.+?)[ \t]*$/m)?.[1]);
  if (top) out.push(top);
  const fe = yml.match(/^frontend:[ \t]*\r?\n((?:[ \t]+.*(?:\r?\n|$))+)/m)?.[1] ?? "";
  const nested = clean(fe.match(/^[ \t]+entry:[ \t]*(.+?)[ \t]*$/m)?.[1]);
  if (nested) out.push(nested);
  return out.map((p) => path3.posix.normalize(p.replace(/\\/g, "/")).replace(/^\.\//, ""));
}
var INSTALL_BLOCK_RULES = /* @__PURE__ */ new Set(["sandbox-escape", "host-transport-escape"]);
var INSTALL_WARN_RULES = /* @__PURE__ */ new Set(["inline-zoto-declare", "pack-zoto-binding"]);
function packIdFromPluginYml(packDirAbs) {
  try {
    const yml = fs3.readFileSync(path3.join(packDirAbs, "plugin.yml"), "utf8");
    const id = yml.match(/^id:\s*(\S+)/m)?.[1];
    return id ?? null;
  } catch {
    return null;
  }
}
function scanPackInstallLint(packDirAbs, repoRoot) {
  const packId = packIdFromPluginYml(packDirAbs) ?? path3.basename(packDirAbs);
  const violations = scanPackDirectory(packDirAbs, repoRoot, {
    packId,
    repoPathPrefix: `plugins/src/${packId}`,
    frontendScripts: true
  });
  const legacyBlocks = legacyZotoViolationsOnDisallowedPacks(violations);
  const legacyBlockKeys = new Set(legacyBlocks.map(violationKey));
  const blocks = [
    ...violations.filter((v) => INSTALL_BLOCK_RULES.has(v.rule)),
    ...legacyBlocks
  ];
  const warnings = violations.filter(
    (v) => INSTALL_WARN_RULES.has(v.rule) && !legacyBlockKeys.has(violationKey(v))
  );
  return { blocks, warnings };
}
function scanPackDirectory(packDirAbs, repoRoot, opts = {}) {
  const packId = opts.packId ?? path3.basename(packDirAbs);
  const repoPrefix = opts.repoPathPrefix ?? `plugins/src/${packId}`;
  const violations = [...symlinkViolations(packDirAbs, repoPrefix, repoRoot)];
  const entries = new Set(opts.frontendScripts ? manifestFrontendEntries(packDirAbs) : []);
  const lintable = (sub, name) => {
    if (isTsSource(name)) return true;
    if (!opts.frontendScripts) return false;
    return entries.has(sub) || sub.startsWith("frontend/") && isFrontendScript(name);
  };
  const walk = (rel) => {
    const dir = path3.join(packDirAbs, rel);
    for (const ent of fs3.readdirSync(dir, { withFileTypes: true })) {
      const sub = rel ? `${rel}/${ent.name}` : ent.name;
      if (ent.isDirectory()) walk(sub);
      else if (lintable(sub, ent.name)) {
        const repoRel = `${repoPrefix}/${sub}`.replace(/\\/g, "/");
        const text = fs3.readFileSync(path3.join(packDirAbs, sub), "utf8");
        violations.push(
          ...lintPackSource(
            repoRel,
            text,
            repoPrefix,
            repoRoot,
            path3.dirname(path3.join(packDirAbs, sub)),
            packDirAbs
          )
        );
      }
    }
  };
  walk("");
  return violations;
}

// plugins/sdk/pack-install-lint.ts
var UNBUNDLED_SCRIPT_RE = /\.(?:js|mjs|cjs|jsx)$/;
function logLine(v) {
  const loc = v.line != null ? `${v.file}:${v.line}` : v.file;
  return `${loc} ${v.rule} — ${formatViolationMessage(v)}`;
}
function unbundledScripts(packDirAbs) {
  const out = /* @__PURE__ */ new Set();
  const walk = (rel) => {
    let ents;
    try {
      ents = fs4.readdirSync(path4.join(packDirAbs, rel), { withFileTypes: true });
    } catch {
      return;
    }
    for (const ent of ents) {
      const sub = `${rel}/${ent.name}`;
      if (ent.isDirectory()) walk(sub);
      else if (UNBUNDLED_SCRIPT_RE.test(ent.name)) out.add(sub);
    }
  };
  walk("frontend");
  for (const entry of manifestFrontendEntries(packDirAbs)) {
    if (fs4.existsSync(path4.join(packDirAbs, entry))) out.add(entry);
  }
  return [...out].sort();
}
function unbundledImportBoundary(packDirAbs, repoRoot) {
  const sdkRoot = path4.join(repoRoot, "plugins/sdk");
  for (const rel of unbundledScripts(packDirAbs)) {
    const abs = path4.join(packDirAbs, rel);
    const text = fs4.readFileSync(abs, "utf8");
    for (const site of extractPackImports(text)) {
      if (site.kind === "unverified") continue;
      const r = resolvePackBundleImport({ specifier: site.specifier, importerFile: abs, packHome: packDirAbs, sdkRoot, repoRoot });
      if (!r.ok) return { file: rel, import: site.specifier, reason: r.reason };
    }
  }
  return null;
}
function runPackInstallLint(packDirAbs, repoRoot, opts = {}) {
  const { blocks, warnings: warn } = scanPackInstallLint(packDirAbs, repoRoot);
  const warnings = warn.map(logLine);
  if (blocks.length > 0) {
    return { kind: "block", message: plainBlockSummary(blocks), details: blocks.map(logLine), warnings };
  }
  if (opts.unbundled) {
    const hit = unbundledImportBoundary(packDirAbs, repoRoot);
    if (hit) return { kind: "boundary", ...hit, warnings };
  }
  return { kind: "pass", warnings };
}
export {
  runPackInstallLint,
  unbundledImportBoundary
};
export const PACK_INSTALL_LINT_BUILD = {
  "entry": "plugins/sdk/pack-install-lint.ts",
  "inputs": [
    "plugins/sdk/host-pack-src-import-allowlist.ts",
    "plugins/sdk/legacy-zoto-pack-allowlist.ts",
    "plugins/sdk/pack-bundle-resolve.mjs",
    "plugins/sdk/pack-install-lint.ts",
    "plugins/sdk/pack-lint-hints.ts",
    "plugins/sdk/pack-lint-host.ts",
    "plugins/sdk/pack-lint-import.ts",
    "plugins/sdk/pack-lint-types.ts",
    "plugins/sdk/pack-lint.ts",
    "plugins/sdk/viz-zoto.ts"
  ],
  "sha256": "2a60b022efff87866f797f87106a64f3fe51377b40d342bc7781e784740bef37"
};
