/**
 * #186: the pack install lint as one in-process call.
 *
 * `web/scripts/build-pack-install-lint.mjs` prebuilds this module (and everything it imports) with
 * esbuild into the plain ESM file `web/scripts/pack-install-lint.built.mjs`, which
 * `bundle-pack-entry.mjs` imports directly. Installing a pack needs no TypeScript runner, and the
 * verdict is this function's return value: there is no child process, exit code or stdout line to
 * lose, kill or fake. The built file is committed and regenerated by web/'s `prepare` script;
 * `pack-install-lint-prebuilt.test.ts` fails when it doesn't match a fresh build of these sources.
 *
 * The install lint deliberately never reads `pack-lint-baseline.json`: the baseline is a CI ratchet
 * for the shipped tree, never an install-time allow-list.
 */
import fs from "node:fs";
import path from "node:path";
import { resolvePackBundleImport } from "./pack-bundle-resolve.mjs";
import { manifestFrontendEntries, scanPackInstallLint } from "./pack-lint";
import { formatViolationMessage, plainBlockSummary } from "./pack-lint-hints";
import { extractPackImports } from "./pack-lint-import";
import { UNIFORM_BLOCKING_RULES, type PackLintViolation } from "./pack-lint-types";
import { lintInstalledPackUniforms } from "./pack-lint-uniforms";

export type PackInstallLintOptions = {
  /**
   * The pack's frontend is served as is (`frontend.bundle: false`, or no frontend): esbuild's
   * import-boundary check never sees it, so run the same resolver over its scripts here.
   */
  unbundled?: boolean;
};

/** Where an unbundled frontend loads code from outside the pack (and the SDK), as esbuild would refuse it. */
export type PackInstallBoundaryHit = { file: string; import: string; reason: string };

/**
 * #194: the block reason when an unbundled frontend calls `import()` with anything but a plain string
 * (a variable, a template with `${}`, a concatenation). Nothing bundles such a pack, so neither esbuild
 * nor the resolver can see what that call loads.
 */
export const DYNAMIC_IMPORT_NONLITERAL = "dynamic_import_nonliteral";

/**
 * #171 (b): the block reason when every finding is a blocking uniform rule (graphics code that would
 * stop the pack drawing). The service then ends the user text with "Ask its author for a fixed
 * version." instead of #185's "run pack lint" tail. A block that also has another finding has no reason.
 */
export const GRAPHICS_CODE_ERROR = "graphics_code_error";

/** Where an unbundled frontend calls `import()` with a non-literal argument. */
export type PackInstallNonLiteralImport = { file: string; line: number; import: string };

export type PackInstallLintVerdict =
  | { kind: "pass"; warnings: string[] }
  /**
   * `message` is the plain sentence for "<Name> was blocked because <message> …"; `details` are for the
   * log. `reason` is set for install-only refusals that aren't a pack-lint rule (#194), and for a
   * block made only of blocking uniform rules (#171 (b), {@link GRAPHICS_CODE_ERROR}).
   */
  | {
      kind: "block";
      message: string;
      details: string[];
      warnings: string[];
      reason?: typeof DYNAMIC_IMPORT_NONLITERAL | typeof GRAPHICS_CODE_ERROR;
    }
  | ({ kind: "boundary"; warnings: string[] } & PackInstallBoundaryHit);

/** Scripts a browser runs as is (so not `.ts` / `.tsx` / `.mts` / `.cts`, which only a bundle serves). */
const UNBUNDLED_SCRIPT_RE = /\.(?:js|mjs|cjs|jsx)$/;

function logLine(v: PackLintViolation): string {
  const loc = v.line != null ? `${v.file}:${v.line}` : v.file;
  return `${loc} ${v.rule} — ${formatViolationMessage(v)}`;
}

/** Pack-relative scripts an unbundled frontend serves: `frontend/**` JS plus whatever plugin.yml names. */
function unbundledScripts(packDirAbs: string): string[] {
  const out = new Set<string>();
  const walk = (rel: string) => {
    let ents: fs.Dirent[];
    try {
      ents = fs.readdirSync(path.join(packDirAbs, rel), { withFileTypes: true });
    } catch {
      return;
    }
    for (const ent of ents) {
      const sub = `${rel}/${ent.name}`;
      if (ent.isDirectory()) walk(sub);
      else if (UNBUNDLED_SCRIPT_RE.test(ent.name)) out.add(sub);
    }
  };
  walk("frontend");
  for (const entry of manifestFrontendEntries(packDirAbs)) {
    if (fs.existsSync(path.join(packDirAbs, entry))) out.add(entry);
  }
  return [...out].sort();
}

/**
 * #186: esbuild's import-boundary check (`pack-bundle-resolve.mjs`, the resolver bundle-pack-entry.mjs
 * uses) over an unbundled frontend's scripts. First hit, in file order; null when every import stays
 * inside the pack or plugins/sdk. Non-literal `import()` can't be resolved here; #194's
 * `unbundledNonLiteralImport` refuses it instead.
 */
export function unbundledImportBoundary(packDirAbs: string, repoRoot: string): PackInstallBoundaryHit | null {
  const sdkRoot = path.join(repoRoot, "plugins/sdk");
  for (const rel of unbundledScripts(packDirAbs)) {
    const abs = path.join(packDirAbs, rel);
    const text = fs.readFileSync(abs, "utf8");
    for (const site of extractPackImports(text)) {
      if (site.kind === "unverified") continue;
      const r = resolvePackBundleImport({ specifier: site.specifier, importerFile: abs, packHome: packDirAbs, sdkRoot, repoRoot });
      if (!r.ok) return { file: rel, import: site.specifier, reason: r.reason };
    }
  }
  return null;
}

/**
 * #194: the first `import()` in an unbundled frontend whose argument isn't a plain string literal, in
 * file order; null when there is none. (`require()` doesn't exist in a browser, so only `import()`.)
 */
export function unbundledNonLiteralImport(packDirAbs: string): PackInstallNonLiteralImport | null {
  for (const rel of unbundledScripts(packDirAbs)) {
    const text = fs.readFileSync(path.join(packDirAbs, rel), "utf8");
    for (const site of extractPackImports(text)) {
      if (site.kind !== "unverified" || site.call !== "import") continue;
      return { file: rel, line: text.slice(0, site.index).split("\n").length, import: site.raw };
    }
  }
  return null;
}

/** The install verdict for an unpacked pack home. Throws only if the check itself breaks (the caller refuses). */
export function runPackInstallLint(
  packDirAbs: string,
  repoRoot: string,
  opts: PackInstallLintOptions = {},
): PackInstallLintVerdict {
  const { blocks, warnings: warn } = scanPackInstallLint(packDirAbs, repoRoot, { uniforms: lintInstalledPackUniforms });
  const warnings = warn.map(logLine);
  if (blocks.length > 0) {
    // #185: `message` is plain words only; the raw file:line rule lines are diagnostics for the log.
    const message = plainBlockSummary(blocks);
    const details = blocks.map(logLine);
    // #171 (b): only graphics code that would stop the pack drawing; a mixed block keeps #185's copy.
    if (blocks.every((v) => UNIFORM_BLOCKING_RULES.has(v.rule))) {
      return { kind: "block", reason: GRAPHICS_CODE_ERROR, message, details, warnings };
    }
    return { kind: "block", message, details, warnings };
  }
  if (opts.unbundled) {
    const hit = unbundledImportBoundary(packDirAbs, repoRoot);
    if (hit) return { kind: "boundary", ...hit, warnings };
    const dyn = unbundledNonLiteralImport(packDirAbs);
    if (dyn) {
      return {
        kind: "block",
        reason: DYNAMIC_IMPORT_NONLITERAL,
        // Copy: pack lint's plain sentence for a non-literal import (PACK_LINT_PLAIN_SUMMARY); UX Pro owns it.
        message: plainBlockSummary([{ rule: "unverified-import-call" }]),
        details: [`${dyn.file}:${dyn.line} ${DYNAMIC_IMPORT_NONLITERAL} — ${dyn.import}`],
        warnings,
      };
    }
  }
  return { kind: "pass", warnings };
}
